### ISSUE TITLE
Issue with Faiss INDEX creation

### ISSUE THREAD

**Issue by sriharsha8991** [krishnaik06/Complete-Langchain-Tutorials#6]
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory

The Streamlit application for Chat with multiple PDFs has the issue while running I tried Figuring it out by manually creating a folder, hope sort it out soon

**Comment by maxzod** [comment]
i have the same problem , fixed by uploading files and process then use the chat

**Comment by sriharsha8991** [comment]
Thank you @maxzod  got the Solution
